/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as ShopSlugRouteImport } from './routes/shop_.$slug'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as PaymentCardRouteImport } from './routes/payment.card'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangShopIndexRouteImport } from './routes/$lang.shop.index'
import { Route as LangBlogIndexRouteImport } from './routes/$lang.blog.index'
import { Route as LangShopSlugRouteImport } from './routes/$lang.shop.$slug'
import { Route as LangBlogSlugRouteImport } from './routes/$lang.blog.$slug'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop_/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCardRoute = PaymentCardRouteImport.update({
  id: '/payment/card',
  path: '/payment/card',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/admin/fees',
  path: '/admin/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangShopIndexRoute = LangShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogIndexRoute = LangBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LangRoute,
} as any)
const LangShopSlugRoute = LangShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogSlugRoute = LangBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/payment/card': typeof PaymentCardRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/shop/$slug': typeof LangShopSlugRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/shop/': typeof LangShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/payment/card': typeof PaymentCardRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/shop/$slug': typeof LangShopSlugRoute
  '/$lang/blog': typeof LangBlogIndexRoute
  '/$lang/shop': typeof LangShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/payment/card': typeof PaymentCardRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/shop_/$slug': typeof ShopSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/shop/$slug': typeof LangShopSlugRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/shop/': typeof LangShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/about'
    | '/blog'
    | '/contact'
    | '/shop'
    | '/$lang/about'
    | '/$lang/contact'
    | '/admin/fees'
    | '/admin/orders'
    | '/admin/products'
    | '/blog/$slug'
    | '/payment/card'
    | '/payment/failed'
    | '/payment/success'
    | '/shop/$slug'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/shop/$slug'
    | '/$lang/blog/'
    | '/$lang/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/shop'
    | '/$lang/about'
    | '/$lang/contact'
    | '/admin/fees'
    | '/admin/orders'
    | '/admin/products'
    | '/blog/$slug'
    | '/payment/card'
    | '/payment/failed'
    | '/payment/success'
    | '/shop/$slug'
    | '/$lang'
    | '/$lang/blog/$slug'
    | '/$lang/shop/$slug'
    | '/$lang/blog'
    | '/$lang/shop'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/about'
    | '/blog'
    | '/contact'
    | '/shop'
    | '/$lang/about'
    | '/$lang/contact'
    | '/admin/fees'
    | '/admin/orders'
    | '/admin/products'
    | '/blog_/$slug'
    | '/payment/card'
    | '/payment/failed'
    | '/payment/success'
    | '/shop_/$slug'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/shop/$slug'
    | '/$lang/blog/'
    | '/$lang/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PaymentCardRoute: typeof PaymentCardRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ShopSlugRoute: typeof ShopSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/shop_/$slug': {
      id: '/shop_/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/card': {
      id: '/payment/card'
      path: '/payment/card'
      fullPath: '/payment/card'
      preLoaderRoute: typeof PaymentCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/admin/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/shop/': {
      id: '/$lang/shop/'
      path: '/shop'
      fullPath: '/$lang/shop/'
      preLoaderRoute: typeof LangShopIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog/': {
      id: '/$lang/blog/'
      path: '/blog'
      fullPath: '/$lang/blog/'
      preLoaderRoute: typeof LangBlogIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/shop/$slug': {
      id: '/$lang/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/$lang/shop/$slug'
      preLoaderRoute: typeof LangShopSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog/$slug': {
      id: '/$lang/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangBlogSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangIndexRoute: typeof LangIndexRoute
  LangBlogSlugRoute: typeof LangBlogSlugRoute
  LangShopSlugRoute: typeof LangShopSlugRoute
  LangBlogIndexRoute: typeof LangBlogIndexRoute
  LangShopIndexRoute: typeof LangShopIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangIndexRoute: LangIndexRoute,
  LangBlogSlugRoute: LangBlogSlugRoute,
  LangShopSlugRoute: LangShopSlugRoute,
  LangBlogIndexRoute: LangBlogIndexRoute,
  LangShopIndexRoute: LangShopIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  BlogSlugRoute: BlogSlugRoute,
  PaymentCardRoute: PaymentCardRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ShopSlugRoute: ShopSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
